/**
 * Research Peptides UK — Initial Certified Catalogue & Master Data
 * Strictly in-vitro laboratory documentation. No human dosing or administration content.
 */

import {
  Product,
  ProductCategory,
  Order,
  Coupon,
  ProductBatch,
  AuditLogEntry,
  InventoryTransaction,
} from '../types';
import { INITIAL_CATEGORIES } from './data/categories';
import { ALL_CATALOGUE_PRODUCTS } from './data/all-products';
import { INITIAL_SHIPPING_METHODS } from './shipping-methods';

export { INITIAL_CATEGORIES, INITIAL_SHIPPING_METHODS };
export const INITIAL_PRODUCTS: Product[] = ALL_CATALOGUE_PRODUCTS;

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'cpn-research10',
    code: 'RESEARCH10',
    description: '10% Institutional Laboratory Research Allowance',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minSpend: 0,
    maxDiscount: 150,
    usageLimit: 500,
    usedCount: 38,
    perUserLimit: 3,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cpn-cambridge5',
    code: 'CAMBRIDGE5',
    description: '£5.00 Welcome Voucher for New Registered Facilities',
    discountType: 'FIXED',
    discountValue: 5,
    minSpend: 30,
    usageLimit: 1000,
    usedCount: 14,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cpn-institution20',
    code: 'INSTITUTION20',
    description: '20% Major Volume Academic Grant Discount',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    minSpend: 250,
    maxDiscount: 500,
    usageLimit: 50,
    usedCount: 5,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_PAYMENTS: any[] = [
  {
    id: 'pay-101',
    orderId: 'ord-101',
    orderNumber: 'RP-2026-8941',
    method: 'BANK_TRANSFER',
    amount: 87.24,
    currency: 'GBP',
    status: 'VERIFIED',
    reference: 'RP-BK-8941',
    transactionHash: 'FASTER-PAY-OXF-9921',
    evidenceNotes: 'Faster Payments remittance receipt ref FP88291 confirmed in Barclays statement.',
    bankDetails: {
      accountName: 'Research Peptides UK Ltd',
      accountNumber: '83920194',
      sortCode: '20-00-00',
      bankName: 'Barclays Commercial UK',
      reference: 'RP-BK-8941',
    },
    submittedAt: '2026-02-14T11:45:00.000Z',
    verifiedAt: '2026-02-14T14:45:00.000Z',
    verifiedBy: 'lab.director@researchpeptides.co.uk',
    notes: 'Reconciled in bank ledger with match on Oxford Biochemistry reference.',
    createdAt: '2026-02-14T11:20:00.000Z',
    updatedAt: '2026-02-14T14:45:00.000Z',
  },
  {
    id: 'pay-102',
    orderId: 'ord-102',
    orderNumber: 'RP-2026-8942',
    method: 'CRYPTOCURRENCY',
    amount: 132.05,
    currency: 'GBP',
    status: 'SUBMITTED',
    reference: 'RP-CRYPTO-8942',
    transactionHash: 'BTC-TX-89f41029cba8e83910385bf',
    evidenceNotes: 'Bitcoin transaction hash submitted by investigator via checkout.',
    cryptoDetails: {
      network: 'BTC',
      walletAddress: 'bc1q9v8084z65k90c7405g7620h5s9v65k8h8w3s92',
      cryptoAmount: '0.00165 BTC',
      exchangeRateSnapshot: '1 BTC = £80,030.30 GBP',
      expiresAt: '2026-02-16T09:12:00.000Z',
    },
    submittedAt: '2026-02-15T09:18:00.000Z',
    notes: 'Awaiting blockchain confirmation / manual mempool verification.',
    createdAt: '2026-02-15T09:12:00.000Z',
    updatedAt: '2026-02-15T09:18:00.000Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'RP-2026-8941',
    customerId: 'usr-customer-1',
    customerEmail: 'dr.harrison@oxford-biochem.ac.uk',
    customerName: 'Dr. Arthur Harrison',
    shippingAddress: {
      fullName: 'Dr. Arthur Harrison',
      institution: 'Oxford Department of Biochemistry',
      addressLine1: 'South Parks Road, Laboratory Wing B',
      city: 'Oxford',
      county: 'Oxfordshire',
      postcode: 'OX1 3QU',
      country: 'GB',
      countryName: 'United Kingdom (Mainland)',
      phone: '+44 1865 275263',
      email: 'dr.harrison@oxford-biochem.ac.uk',
    },
    items: [
      {
        id: 'oi-1',
        productId: 'prod-bpc157',
        variantId: 'var-bpc157-5mg',
        productName: 'BPC-157 Reference Standard',
        variantName: '5mg Lyophilized Vial',
        sku: 'RPUK-BPC157',
        variantSku: 'RPUK-BPC157-5MG',
        size: '5mg',
        quantity: 3,
        unitPrice: 13.95,
        tierDiscountAmount: 0,
        allocatedCouponDiscountAmount: 4.18,
        allocatedCryptoDiscountAmount: 0,
        totalPrice: 37.67,
      },
      {
        id: 'oi-2',
        productId: 'prod-bac-water-30ml',
        variantId: 'var-bac30-single',
        productName: 'Bacteriostatic Water for Injection (30mL Vial)',
        variantName: '30mL Sterile Multi-Dose Vial',
        sku: 'RPUK-BAC30',
        variantSku: 'RPUK-BAC30-1',
        size: '30ml',
        quantity: 2,
        unitPrice: 8.95,
        tierDiscountAmount: 0,
        allocatedCouponDiscountAmount: 1.79,
        allocatedCryptoDiscountAmount: 0,
        totalPrice: 16.11,
      },
    ],
    subtotal: 59.75,
    tierDiscountAmount: 0,
    couponCode: 'RESEARCH10',
    couponDiscountAmount: 5.97,
    cryptoDiscountAmount: 0,
    shippingMethodId: 'ship-uk-standard',
    shippingMethodName: 'Royal Mail Tracked 24 (Next Business Day)',
    shippingCarrier: 'Royal Mail',
    shippingZone: 'UK_MAINLAND',
    shippingFee: 4.99,
    total: 58.77,
    currency: 'GBP',
    paymentId: 'pay-101',
    paymentMethod: 'BANK_TRANSFER',
    paymentStatus: 'VERIFIED',
    status: 'PAYMENT_VERIFIED',
    paymentProofReference: 'FASTER-PAY-OXF-9921',
    courier: 'Royal Mail Tracked 24',
    trackingNumber: 'GB-RM-2026-902144',
    trackingUrl: 'https://www.royalmail.com/track-your-item#/tracking-results/GB-RM-2026-902144',
    researchConsentSigned: true,
    history: [
      {
        id: 'h-1',
        orderId: 'ord-101',
        timestamp: '2026-02-14T11:20:00.000Z',
        fromStatus: 'DRAFT',
        toStatus: 'PENDING_PAYMENT',
        actor: 'Dr. Arthur Harrison',
        actorRole: 'CUSTOMER',
        note: 'Order placed with Bank Transfer payment method.',
      },
      {
        id: 'h-2',
        orderId: 'ord-101',
        timestamp: '2026-02-14T11:45:00.000Z',
        fromStatus: 'PENDING_PAYMENT',
        toStatus: 'PAYMENT_SUBMITTED',
        actor: 'Dr. Arthur Harrison',
        actorRole: 'CUSTOMER',
        note: 'Customer submitted Faster Payments transfer reference FASTER-PAY-OXF-9921.',
      },
      {
        id: 'h-3',
        orderId: 'ord-101',
        timestamp: '2026-02-14T14:45:00.000Z',
        fromStatus: 'PAYMENT_SUBMITTED',
        toStatus: 'PAYMENT_VERIFIED',
        actor: 'Chief Scientific Officer (Admin)',
        actorRole: 'ADMIN',
        note: 'Payment verified in Barclays bank ledger.',
      },
    ],
    createdAt: '2026-02-14T11:20:00.000Z',
    updatedAt: '2026-02-14T14:45:00.000Z',
  },
  {
    id: 'ord-102',
    orderNumber: 'RP-2026-8942',
    customerId: 'usr-customer-2',
    customerEmail: 'e.davies@cambridge-cell.org',
    customerName: 'Elena Davies, MSc',
    shippingAddress: {
      fullName: 'Elena Davies, MSc',
      institution: 'Cambridge Cellular Therapeutics Ltd',
      addressLine1: 'Cambridge Science Park, Innovation Hub 4',
      city: 'Cambridge',
      county: 'Cambridgeshire',
      postcode: 'CB4 0GF',
      country: 'GB',
      countryName: 'United Kingdom (Mainland)',
      phone: '+44 1223 908122',
      email: 'e.davies@cambridge-cell.org',
    },
    items: [
      {
        id: 'oi-3',
        productId: 'prod-tirzepatide',
        variantId: 'var-tirz-10mg',
        productName: 'Tirzepatide Reference Standard (Dual GIP/GLP-1)',
        variantName: '10mg Lyophilized Vial',
        sku: 'RPUK-TIRZ',
        variantSku: 'RPUK-TIRZ-10MG',
        size: '10mg',
        quantity: 1,
        unitPrice: 44.95,
        tierDiscountAmount: 0,
        allocatedCouponDiscountAmount: 0,
        allocatedCryptoDiscountAmount: 2.25,
        totalPrice: 42.7,
      },
    ],
    subtotal: 44.95,
    tierDiscountAmount: 0,
    couponDiscountAmount: 0,
    cryptoDiscountAmount: 2.25,
    shippingMethodId: 'ship-uk-standard',
    shippingMethodName: 'Royal Mail Tracked 24 (Next Business Day)',
    shippingCarrier: 'Royal Mail',
    shippingZone: 'UK_MAINLAND',
    shippingFee: 4.99,
    total: 47.69,
    currency: 'GBP',
    paymentId: 'pay-102',
    paymentMethod: 'CRYPTOCURRENCY',
    paymentStatus: 'SUBMITTED',
    status: 'PAYMENT_SUBMITTED',
    paymentProofReference: 'BTC-TX-89f41029cba8',
    researchConsentSigned: true,
    history: [
      {
        id: 'h-4',
        orderId: 'ord-102',
        timestamp: '2026-02-15T09:12:00.000Z',
        fromStatus: 'DRAFT',
        toStatus: 'PENDING_PAYMENT',
        actor: 'Elena Davies, MSc',
        actorRole: 'CUSTOMER',
        note: 'Order created with 5% cryptocurrency settlement incentive.',
      },
      {
        id: 'h-5',
        orderId: 'ord-102',
        timestamp: '2026-02-15T09:18:00.000Z',
        fromStatus: 'PENDING_PAYMENT',
        toStatus: 'PAYMENT_SUBMITTED',
        actor: 'Elena Davies, MSc',
        actorRole: 'CUSTOMER',
        note: 'Customer submitted BTC transaction hash.',
      },
    ],
    createdAt: '2026-02-15T09:12:00.000Z',
    updatedAt: '2026-02-15T09:18:00.000Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-1',
    actor: 'compliance@researchpeptides.co.uk',
    action: 'PRODUCT_PUBLISHED',
    entityType: 'PRODUCT',
    entityId: 'prod-bpc157',
    payload: { name: 'BPC-157 Reference Standard', status: 'PUBLISHED', purity: 99.42 },
    ipAddress: '192.168.1.10',
    createdAt: '2026-01-10T12:00:00.000Z',
  },
  {
    id: 'log-2',
    actor: 'lab@researchpeptides.co.uk',
    action: 'COA_DOCUMENT_UPLOADED',
    entityType: 'DOCUMENT',
    entityId: 'doc-bpc-coa',
    payload: { documentType: 'COA', batchNumber: 'UK-2026-B892' },
    ipAddress: '192.168.1.12',
    createdAt: '2026-01-23T09:00:00.000Z',
  },
  {
    id: 'log-3',
    actor: 'admin@researchpeptides.co.uk',
    action: 'COUPON_CREATED',
    entityType: 'COUPON',
    entityId: 'cpn-research10',
    payload: { code: 'RESEARCH10', discountValue: 10 },
    ipAddress: '192.168.1.10',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_INVENTORY_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: 'inv-tx-1',
    variantId: 'var-bpc157-5mg',
    transactionType: 'RESTOCK',
    quantityChange: 150,
    balanceAfter: 150,
    notes: 'Initial production batch UK-2026-B892 received from synthesis core.',
    actorEmail: 'lab@researchpeptides.co.uk',
    createdAt: '2026-01-10T08:00:00.000Z',
  },
  {
    id: 'inv-tx-2',
    variantId: 'var-bpc157-5mg',
    orderId: 'ord-101',
    transactionType: 'RESERVATION',
    quantityChange: -3,
    balanceAfter: 147,
    notes: 'Order RP-2026-8941 inventory lock.',
    actorEmail: 'dr.harrison@oxford-biochem.ac.uk',
    createdAt: '2026-02-14T11:20:00.000Z',
  },
  {
    id: 'inv-tx-3',
    variantId: 'var-bac30-single',
    transactionType: 'RESTOCK',
    quantityChange: 200,
    balanceAfter: 200,
    notes: 'Sterile solvent batch lot verified.',
    actorEmail: 'lab@researchpeptides.co.uk',
    createdAt: '2026-01-05T09:00:00.000Z',
  },
  {
    id: 'inv-tx-4',
    variantId: 'var-tirz-10mg',
    orderId: 'ord-102',
    transactionType: 'RESERVATION',
    quantityChange: -1,
    balanceAfter: 64,
    notes: 'Order RP-2026-8942 crypto checkout reservation.',
    actorEmail: 'e.davies@cambridge-cell.org',
    createdAt: '2026-02-15T09:12:00.000Z',
  },
];
