/** Extra listings withdrawn from the storefront. Old URLs canonicalize to /shop. */
export const REMOVED_PRODUCT_SLUGS = new Set([
  'semax-analytical-nasal-spray-30mg',
  'bacteriostatic-water-5x-30ml-pack',
  'melanotan-2-analytical-spray-solution-30mg',
  'manual-20mm-vial-hand-crimper-tool',
  'kisspeptin-10-analytical-nasal-spray-20mg',
  'sterile-glass-vials-20ml-pack-of-10',
  'bpc-157-analytical-nasal-spray-30mg',
  'bpc-157-tb-500-dual-nasal-spray-60mg',
  'selank-analytical-nasal-spray-30mg',
  'nad-plus-analytical-spray-500mg',
  'nad-plus-high-concentration-spray-1000mg',
  'pt-141-bremelanotide-nasal-spray-30mg',
  'oxytocin-analytical-solution-spray-10mg',
  'bacteriostatic-water-30ml-vial',
  'sterile-analytical-saline-09-nacl-30ml',
  '10mm-acetic-acid-peptide-solvent-30ml',
  'sterile-analytical-deionised-water-30ml',
  '022um-pes-syringe-filters-25pk',
  '022um-pes-syringe-filters-100pk-bulk',
  'sterile-glass-vials-10ml-pack-of-10',
  'precision-analytical-micro-pipette-10-100ul',
]);
