/**
 * Additive commerce DDL for Neon. Safe to re-run. Does not drop data.
 */

export const COMMERCE_SCHEMA_STATEMENTS: string[] = [
  `CREATE TYPE user_role AS ENUM ('CUSTOMER', 'ADMIN', 'ANALYST')`,
  `CREATE TYPE payment_method AS ENUM ('BANK_TRANSFER', 'CRYPTOCURRENCY')`,
  `CREATE TYPE order_status AS ENUM ('pending_payment', 'payment_submitted', 'payment_verified', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')`,
  `CREATE TABLE IF NOT EXISTS users (
    id text PRIMARY KEY,
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    name text NOT NULL,
    role user_role NOT NULL DEFAULT 'CUSTOMER',
    institution text,
    vat_number text,
    phone text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS shipping_methods (
    id text PRIMARY KEY,
    name text NOT NULL,
    zone text NOT NULL,
    carrier text NOT NULL,
    price_pence integer NOT NULL,
    free_shipping_threshold_pence integer,
    estimated_days text NOT NULL,
    tracking_available boolean NOT NULL DEFAULT true,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS orders (
    id text PRIMARY KEY,
    order_number text NOT NULL UNIQUE,
    user_id text REFERENCES users(id) ON DELETE SET NULL,
    customer_email text NOT NULL,
    customer_name text NOT NULL,
    subtotal_pence integer NOT NULL,
    tier_discount_pence integer NOT NULL DEFAULT 0,
    coupon_code text,
    coupon_discount_pence integer NOT NULL DEFAULT 0,
    crypto_discount_pence integer NOT NULL DEFAULT 0,
    shipping_method_id text,
    shipping_pence integer NOT NULL,
    total_pence integer NOT NULL,
    currency text NOT NULL DEFAULT 'GBP',
    payment_method payment_method NOT NULL,
    status order_status NOT NULL DEFAULT 'pending_payment',
    payment_proof_reference text,
    tracking_number text,
    research_consent_signed boolean NOT NULL DEFAULT true,
    shipping_address_json text NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    payload_json text,
    app_status text,
    payment_status text,
    idempotency_key text
  )`,
  `CREATE TABLE IF NOT EXISTS order_items (
    id text PRIMARY KEY,
    order_id text NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id text NOT NULL,
    variant_id text NOT NULL,
    sku text NOT NULL,
    product_name text NOT NULL,
    variant_name text NOT NULL,
    quantity integer NOT NULL,
    unit_price_pence integer NOT NULL,
    total_price_pence integer NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS order_payments (
    id text PRIMARY KEY,
    order_id text NOT NULL,
    method text NOT NULL,
    amount_pence integer NOT NULL,
    currency text NOT NULL DEFAULT 'GBP',
    status text NOT NULL,
    reference text,
    transaction_hash text,
    evidence_notes text,
    payload_json text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS inventory_events (
    id text PRIMARY KEY,
    variant_id text NOT NULL,
    order_id text,
    transaction_type text NOT NULL,
    quantity_change integer NOT NULL,
    balance_after integer NOT NULL,
    notes text,
    actor_id text,
    payload_json text,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS store_settings (
    id text PRIMARY KEY,
    payload_json text NOT NULL,
    updated_at timestamp NOT NULL DEFAULT now(),
    updated_by text
  )`,
  `CREATE TABLE IF NOT EXISTS product_merchandising (
    product_id text PRIMARY KEY,
    featured boolean NOT NULL DEFAULT false,
    bestseller_override boolean NOT NULL DEFAULT false,
    bestseller_excluded boolean NOT NULL DEFAULT false,
    new_arrival_override boolean NOT NULL DEFAULT false,
    hide_from_homepage boolean NOT NULL DEFAULT false,
    merchandising_priority integer NOT NULL DEFAULT 0,
    merchandising_updated_at timestamp NOT NULL DEFAULT now(),
    merchandising_updated_by text
  )`,
  `CREATE TABLE IF NOT EXISTS merchandising_audit (
    id text PRIMARY KEY,
    actor text NOT NULL,
    actor_id text,
    product_id text NOT NULL,
    action text NOT NULL,
    old_value text,
    new_value text,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS contact_messages (
    id text PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    subject text,
    message text NOT NULL,
    consent boolean NOT NULL,
    status text NOT NULL DEFAULT 'NEW',
    idempotency_key text,
    ip_hash text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS newsletter_subscriptions (
    id text PRIMARY KEY,
    email text NOT NULL,
    topics text NOT NULL,
    consent_timestamp timestamp NOT NULL,
    consent_source text NOT NULL,
    status text NOT NULL DEFAULT 'ACTIVE',
    unsubscribe_status text NOT NULL DEFAULT 'SUBSCRIBED',
    provider_status text NOT NULL DEFAULT 'NOT_CONNECTED_TO_EMAIL_PROVIDER',
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id text PRIMARY KEY,
    actor text NOT NULL,
    actor_id text,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    payload_json text,
    ip_address text,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS orders_idempotency_key_idx ON orders (idempotency_key) WHERE idempotency_key IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS orders_user_id_idx ON orders (user_id)`,
  `CREATE INDEX IF NOT EXISTS orders_status_idx ON orders (status)`,
  `CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items (order_id)`,
  `CREATE INDEX IF NOT EXISTS order_payments_order_idx ON order_payments (order_id)`,
  `CREATE INDEX IF NOT EXISTS inventory_events_variant_idx ON inventory_events (variant_id)`,
  `CREATE INDEX IF NOT EXISTS inventory_events_order_idx ON inventory_events (order_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS newsletter_subscriptions_email_idx ON newsletter_subscriptions (email)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS contact_messages_idempotency_idx ON contact_messages (idempotency_key) WHERE idempotency_key IS NOT NULL`,
];
